version: '3.8'

services:
  dbservice:
    image: mysql:8.0.37
    environment:
      - MYSQL_ROOT_PASSWORD=pushpak
    volumes:
      - dbdata:/var/lib/mysql

  back-end:
    build:
      context: ./projectmanagement
      dockerfile: Dockerfile
    image: pushpaky/backend-image:trial
    ports:
      - '5054:5054'
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/projectmanagement?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=pushpak
    depends_on:
      - dbservice

  front-end:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: pushpaky/frontend-image:trial
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host
    depends_on:
      - back-end

volumes:
  dbdata:
